// Static data for development - will be replaced with API calls later

export const mockInfluencers = [
    {
        id: '1',
        name: 'Sarah Johnson',
        email: 'sarah@example.com',
        number: '+1-234-567-8900',
        followers: {
            facebook: 125000,
            instagram: 250000,
            tiktok: 180000,
            youtube: 95000,
        },
        sectors: ['Fashion', 'Beauty', 'Lifestyle'],
        location: 'New York, USA',
        engagementRate: 4.5,
        avatar: '👩‍💼',
    },
    {
        id: '2',
        name: 'Mike Chen',
        email: 'mike@example.com',
        number: '+1-234-567-8901',
        followers: {
            facebook: 85000,
            instagram: 320000,
            tiktok: 450000,
            youtube: 200000,
        },
        sectors: ['Tech', 'Gaming', 'Entertainment'],
        location: 'Los Angeles, USA',
        engagementRate: 5.2,
        avatar: '👨‍💻',
    },
    {
        id: '3',
        name: 'Emma Wilson',
        email: 'emma@example.com',
        number: '+1-234-567-8902',
        followers: {
            facebook: 200000,
            instagram: 180000,
            tiktok: 95000,
            youtube: 120000,
        },
        sectors: ['Fitness', 'Health', 'Wellness'],
        location: 'Miami, USA',
        engagementRate: 4.8,
        avatar: '💪',
    },
    {
        id: '4',
        name: 'Alex Rivera',
        email: 'alex@example.com',
        number: '+1-234-567-8903',
        followers: {
            facebook: 150000,
            instagram: 280000,
            tiktok: 320000,
            youtube: 150000,
        },
        sectors: ['Travel', 'Food', 'Lifestyle'],
        location: 'San Francisco, USA',
        engagementRate: 5.0,
        avatar: '✈️',
    },
    {
        id: '5',
        name: 'Jessica Martinez',
        email: 'jessica@example.com',
        number: '+1-234-567-8904',
        followers: {
            facebook: 95000,
            instagram: 195000,
            tiktok: 240000,
            youtube: 85000,
        },
        sectors: ['Beauty', 'Makeup', 'Fashion'],
        location: 'Chicago, USA',
        engagementRate: 4.7,
        avatar: '💄',
    },
];

export const mockClients = [
    {
        id: '1',
        name: 'TechStart Inc.',
        email: 'contact@techstart.com',
        number: '+1-234-567-8910',
        product: 'Smartphone App for Fitness',
        budget: '$10,000 - $15,000',
        paymentType: 'money',
        expectations: 'Looking for fitness influencers with 100k+ followers',
        sectors: ['Fitness', 'Health', 'Tech'],
        companySize: 'Medium',
        avatar: '🏢',
    },
    {
        id: '2',
        name: 'Fashion Forward',
        email: 'hello@fashionforward.com',
        number: '+1-234-567-8911',
        product: 'Sustainable Clothing Line',
        budget: '$5,000 - $8,000',
        paymentType: 'barter',
        expectations: 'Fashion influencers with eco-conscious audience',
        sectors: ['Fashion', 'Sustainability', 'Lifestyle'],
        companySize: 'Small',
        avatar: '👗',
    },
    {
        id: '3',
        name: 'Gaming Zone',
        email: 'info@gamingzone.com',
        number: '+1-234-567-8912',
        product: 'New Gaming Mouse',
        budget: '$3,000 - $5,000',
        paymentType: 'money',
        expectations: 'Gaming influencers with active streaming channels',
        sectors: ['Gaming', 'Tech', 'Entertainment'],
        companySize: 'Small',
        avatar: '🎮',
    },
];

export const mockAdmins = [
    {
        id: '1',
        name: 'Admin User',
        email: 'admin@influplatform.com',
        role: 'admin',
    },
];

export const sectors = [
    'Fashion',
    'Beauty',
    'Lifestyle',
    'Tech',
    'Gaming',
    'Entertainment',
    'Fitness',
    'Health',
    'Wellness',
    'Travel',
    'Food',
    'Makeup',
    'Sustainability',
];
